// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcDYbzLFh2CdUTFi_yE9JeTtgnoAbxgkU',
    appId: '1:1092033191109:web:206335083a2edd2df6e4ac',
    messagingSenderId: '1092033191109',
    projectId: 'smart-locator-app',
    authDomain: 'smart-locator-app.firebaseapp.com',
    storageBucket: 'smart-locator-app.firebasestorage.app',
    measurementId: 'G-DP6MHPTRFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcXyS3iXQiOU-VXpDbH90MPwjUbSRmMYw',
    appId: '1:1092033191109:android:100c100fc70d3786f6e4ac',
    messagingSenderId: '1092033191109',
    projectId: 'smart-locator-app',
    storageBucket: 'smart-locator-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAysgU5q65eqK5R490CgAKYPd3trXRbE88',
    appId: '1:1092033191109:ios:b0d20b46ebaac613f6e4ac',
    messagingSenderId: '1092033191109',
    projectId: 'smart-locator-app',
    storageBucket: 'smart-locator-app.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAysgU5q65eqK5R490CgAKYPd3trXRbE88',
    appId: '1:1092033191109:ios:b0d20b46ebaac613f6e4ac',
    messagingSenderId: '1092033191109',
    projectId: 'smart-locator-app',
    storageBucket: 'smart-locator-app.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcDYbzLFh2CdUTFi_yE9JeTtgnoAbxgkU',
    appId: '1:1092033191109:web:2849c00dc4d75d8ff6e4ac',
    messagingSenderId: '1092033191109',
    projectId: 'smart-locator-app',
    authDomain: 'smart-locator-app.firebaseapp.com',
    storageBucket: 'smart-locator-app.firebasestorage.app',
    measurementId: 'G-FDGXYZMDYF',
  );

}