import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; 
import 'firebase_options.dart';  // generated by flutterfire
import 'splash_screen.dart';
import 'login_screen.dart';
import 'signup_screen.dart';
import 'customer_dashboard.dart';
import 'shopkeeper_dashboard.dart';
import 'admin_dashboard.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'NearShop App',
      theme: ThemeData(primarySwatch: Colors.blue),
      initialRoute: '/', // Start with SplashScreen
      routes: {
        '/': (context) => SplashScreen(),
        '/login': (context) => LoginScreen(role: 'Customer'), // Default role, role selection ke baad change hoga
        '/signup': (context) => SignupScreen(role: 'Customer'),
        '/customerDashboard': (context) => CustomerDashboard(),
        '/shopkeeperDashboard': (context) => ShopkeeperDashboard(),
        '/adminDashboard': (context) => AdminDashboard(),
      },
    );
  }
}